blueprints/qa.py
from flask import Blueprint,render_template,g,request,redirect,url_for,flash
from decorators import login_required
from .forms import QuestionForm,AnswerForm,WaiMaiForm
from models import CommentModel,AnswerModel,UserModel,XiaDan
from exts import db
from sqlalchemy import or_
from werkzeug.utils import secure_filename
import config
import os
from datetime import datetime



bp = Blueprint("qa",__name__,url_prefix="/")


@bp.route("/")
@login_required
def index():
    comments = CommentModel.query.order_by(db.text('-create_time')).all()
    return render_template("index.html",comments=comments)


@bp.route("/restaurant")
@login_required
def restaurant():
    #判断登录

    return render_template("restaurant.html")


@bp.route("/user_homepage")
@login_required
def user_homepage():
    #判断登录

    return render_template("user_homepage.html")


@bp.route("/rider")
@login_required
def rider():
    #判断登录
    user = g.user
    money = user.money
    waimai = XiaDan.query.order_by(db.text('-create_time')).all()
    return render_template("rider.html",waimai=waimai,money=money)


@bp.route("/admin")
@login_required
def admin():
    #判断登录
    user = UserModel.query.order_by(db.text('-join_time')).all()
    waimai = XiaDan.query.order_by(db.text('-create_time')).all()
    comments = CommentModel.query.all()
    answer = AnswerModel.query.all()
    return render_template("admin.html",user=user,waimai=waimai,comments=comments,answer=answer)


@bp.route("/restaurant",methods=['GET','POST'])
@login_required
def comment():
    #判断登录
    if request.method == 'GET':
        return render_template("restaurant.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
        else:
            flash("标题或内容格式错误！")
            return redirect(url_for("qa.restaurant"))

        icon = request.files.get('icon')
        ALLOWED_EXTENSIONS = ['jpg', 'png', 'gif', 'bmp']
        icon_name = icon.filename
        suffix = icon_name.rsplit('.')[-1]
        if suffix in ALLOWED_EXTENSIONS:
            icon_name = secure_filename(icon_name)
            file_path = os.path.join(config.UPLOAD_ICON_DIR, icon_name)
            # print(file_path)
            icon.save(file_path)
            path = '/upload/icon/'
            icon2 = os.path.join(path, icon_name)
        question = CommentModel(title=title, content=content, author=g.user, icon=icon2)
        db.session.add(question)
        db.session.commit()
        return redirect("/")


@bp.route("/comment/<int:comment_id>")
def comment_detail(comment_id):
    comment = CommentModel.query.get(comment_id)
    return render_template("detail.html",comment=comment)

@bp.route("/answer/<int:comment_id>",methods=['POST'])
def answer(comment_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        answer_model = AnswerModel(content=content, author=g.user, comment_id=comment_id)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for("qa.comment_detail", comment_id=comment_id))
    else:
        flash("表单验证失败！")
        return redirect(url_for("qa.comment_detail", comment_id=comment_id))

@bp.route("/search")
def search():
    q = request.args.get('q')
    comments = CommentModel.query.filter(or_(CommentModel.title.contains(q),CommentModel.content.contains(q)))
    return render_template("index.html",comments=comments)


@bp.route('/user/<username>')
@login_required
def user():

    return render_template('user_homepage.html')

@bp.route('/order',methods=["GET",'POST'])
@login_required
def order():
    if request.method == 'POST':

        return render_template('order.html')
    else:
        return render_template('/')

@bp.route('/delete_comment/<int:comment_id>')
@login_required
def delete_comment(comment_id):
    comment = CommentModel.query.get(comment_id)
    if comment:
        try:
            db.session.delete(comment)
            db.session.commit()
        except Exception as e:

            flash("删除评论出错")
            db.session.rollback()
    else:
        flash("评论找不到")
    return redirect(url_for('qa.index'))

#用户信息修改
@bp.route('/change',methods=['GET','POST'])
@login_required
def user_change():
    if request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            email = request.form.get('email')
            icon = request.files.get('icon')
            # print(icon)
            ALLOWED_EXTENSIONS = ['jpg', 'png', 'gif', 'bmp']
            icon_name = icon.filename
            suffix = icon_name.rsplit('.')[-1]

            if suffix in ALLOWED_EXTENSIONS:
                icon_name = secure_filename(icon_name)
                file_path = os.path.join(config.UPLOAD_ICON_DIR,icon_name)
                print(file_path)
                icon.save(file_path)
                user = g.user
                path = '/upload/icon/'
                user.icon = os.path.join(path,icon_name)
                db.session.commit()
                return redirect(url_for('qa.user_homepage'))
            else:
                render_template('user_homepage.html', user=g.user,msg='必须是jpg,png,gif,bmp格式的文件')
            user = g.user
            user.username = username
            user.password = password
            user.email = email
            db.session.commit()

            # users = UserModel.query.all()
            # for user1 in users:
            #     if user1.email == email:
            #         return render_template('user_homepage.html',user=g.user,msg='此邮箱已被注册')




    return render_template('user_homepage.html',user=g.user)


@bp.route("/send", methods=['GET','POST'])
@login_required
def send():
    if request.method == "GET":
        return render_template("order.html")
    else:
        form = WaiMaiForm(request.form)
        dish = form.dish.data
        delivery_address = form.address.data
        telephone_number = form.telephone.data

        waimai = XiaDan(delivery_address=delivery_address,telephone_number=telephone_number,dish=dish)
        db.session.add(waimai)
        db.session.commit()
        return redirect(url_for("qa.index"))

@bp.route("/take_orders/<int:dish_id>", methods=['GET','POST'])
@login_required
def take_orders(dish_id):
    if request.method == "GET":
        return render_template("rider.html")
    else:
        results = XiaDan.query.all()
        # state = 1
        # arrival_time = datetime.now()
        # dish.state = state
        # dish.arrival_time = arrival_time

        results[dish_id-1].arrival_time = datetime.now()
        results[dish_id-1].state = 1
        user = g.user
        money = user.money
        user.money = money+10
        db.session.commit()
        return redirect(url_for("qa.rider"))

@bp.route('/delete_dish/<int:dish_id>')
@login_required
def delete_dish(dish_id):
    dish =XiaDan.query.get(dish_id)
    if comment:
        try:
            db.session.delete(dish)
            db.session.commit()
        except Exception as e:

            flash("删除评论出错")
            db.session.rollback()
    else:
        flash("评论找不到")
    return redirect(url_for('qa.admin'))

blueprints/user.py
from flask import (
    Blueprint,
    render_template,
    request,redirect,
    url_for,
    jsonify,
    session,
    flash)
from exts import mail,db
from flask_mail import Message
from models import EmailCaptchaModel,UserModel
import string
import random
from datetime import datetime
from .forms import RegisterForm,LoginForm
from werkzeug.security import generate_password_hash,check_password_hash

bp = Blueprint("user",__name__,url_prefix="/user")

@bp.route("/login",methods=["GET",'POST'])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password,password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                flash("邮箱和密码不匹配！")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式错误！")
            return redirect(url_for("user.login"))




@bp.route("/register",methods=['GET','POST'])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data

            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))

@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("user.login"))

@bp.route("/captcha",methods=['POST'])
def get_captcha():
    email = request.form.get("email")
    letters = string.ascii_letters+string.digits
    captcha = "".join(random.sample(letters,4))
    if email:
        message = Message(
            subject="枝江外卖验证码",
            recipients=[email],
            body=f"【枝江外卖】您的注册验证码是{captcha},请不要告诉任何人哦"
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email,captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        print("chptcha:",captcha)
        return jsonify({"code":200})
    else:
        return jsonify(({"code":400,"message":"请先传递邮箱！"}))


@bp.route("/comment", methods=['GET', 'POST'])
def comment():
    if request.method == 'POST':
        return render_template("comments.html")
    return render_template('/')



templates/admin.html
{% extends "base.html" %}

{% block title %}管理员界面{% endblock %}

{% block body %}
  <h1 align="center">管理员界面</h1>
  <h2>管理员您好！</h2>
  <h3>菜品管理</h3>
  {% for comment in comments %}
    <li>

      <div class="question-main">
        <div class="question-title">菜品：
          {{ comment.title }}</div>
        <div>
          <a href="{{ url_for('qa.delete_comment',comment_id=comment.id) }}">删除</a>
        </div>

      </div>
    </li>
  {% endfor %}
    <h3>外卖订单管理</h3>
    {% for waimai1 in waimai %}
    <li>

      <div class="question-main">
        <div class="question-title">订单信息：
          {{ waimai1.dish }}</div>
        <div>
          <a href="{{ url_for('qa.delete_dish',dish_id=waimai1.id) }}">删除</a>
        </div>

      </div>
    </li>
  {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head%}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="#">枝江外卖</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('qa.user_homepage') }}">用户主页</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('qa.restaurant') }}">商家</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('qa.rider') }}">骑手</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('qa.admin') }}">后台</a>
      </li>
        <li class="nav-item ml-2">
            <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('qa.search') }}">
              <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
            </form>
        </li>
    </ul>
      <ul class="navbar-nav">
        {% if user %}
          <li class="nav-item">
            <span class="nav-link">{{user.username}}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
          </li>
        {% endif %}


    </ul>

  </div>
  </div>
</nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

templates/comments.html
{% extends "base.html" %}

{% block title %}评论{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
<div class="col"></div>
<div class="col-8">
  <h1 style="text-align: center;">上传菜品</h1>
  <form action="{{ url_for('qa.restaurant') }}" method="post" enctype="multipart/form-data">
    <div class="form-group">
      <input type="text" name="title" class="form-control" placeholder="请输入菜名">
    </div>
    <div class="form-group">
      <textarea name="content" class="form-control" rows="10" placeholder="请对菜品进行描述"></textarea>
    </div>

    <div>
      <input type="file" id="exampleInputFile" name="icon">
    </div>



    {% for message in get_flashed_messages() %}
      <div class="form-group">
        <div class="text-danger">{{ message }}</div>
      </div>
    {% endfor %}

    <div class="form-group" style="text-align: right;">
      <button class="btn btn-primary">发布</button>
    </div>
  </form>
</div>
<div class="col"></div>
</div>
{% endblock %}

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ comment.title }}{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8" style="background-color: #fff;padding: 20px;">
      <h3 class="page-title">{{ comment.title }}</h3>
      <p class="question-info">
        <span>作者：{{ comment.author.username }}</span>
        <span>时间：{{ comment.create_time }}</span>
      </p>
      <hr>
      <p class="question-content">{{ comment.content }}</p>
      <hr>
      <div>
                <img src="{% if comment.icon %} {{ url_for('static',filename=comment.icon) }} {% endif %}" alt=""
                     width="500" height="500">
      </div>
      <p>

      </p>



      <h4 class="comment-group-title">评论（{{ comment.answers|length }}）：</h4>
      <form action="{{ url_for('qa.answer',comment_id=comment.id) }}" method="post">
        <div class="form-group">
          <input type="text" placeholder="请填写评论" name="content" class="form-control">
        </div>
        {% for message in get_flashed_messages() %}
          <div class="form-group">
            <div class="text-danger">{{ message }}</div>
          </div>
        {% endfor %}
        <div class="form-group" style="text-align: right;">
          <button class="btn btn-primary">评论</button>
        </div>
      </form>

      <ul class="comment-group">
        {% for answer in comment.answers %}
          <li>
            <div class="user-info">
              <img class="avatar" src="{{ url_for('static',filename=answer.author.icon) }}" alt="">
              <span class="username">{{ answer.author.username }}</span>
              <span class="create-time">{{ answer.create_time }}</span>
            </div>
            <p class="comment-content">{{ answer.content }}</p>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}枝江外卖-首页{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8">
      <ul class="question-ul">

        {% for comment in comments %}
          <li>
            <div class="side-question">
              <img class="side-question-avatar" src="{{ url_for('static',filename=comment.author.icon) }}" alt="">
            </div>
            <div class="question-main">
              <div class="question-title"><a
                      href="{{ url_for('qa.comment_detail',comment_id=comment.id) }}">{{ comment.title }}</a></div>
              <div class="question-content">{{ comment.content }}</div>

              <div>
                <img src="{% if comment.icon %} {{ url_for('static',filename=comment.icon) }} {% endif %}" alt=""
                     width="200" height="200">
              </div>

              <div class="question-detail">
                <span class="question-author">{{ comment.author.username }}</span>
                <span class="question-time">{{ comment.create_time }}</span>
              </div>

              <div>
                <a href="{{ url_for('qa.delete_comment',comment_id=comment.id) }}">删除</a>
              </div>

            </div>
          </li>
        {% endfor %}

        <form action="{{ url_for('qa.order') }}" method="post">
          <div style="text-align: right;">
            <button type="submit" class="btn btn-primary">下单</button>
          </div>
        </form>
      </ul>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}外卖平台-用户登录{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
  <div class="row mt-4">
    <div class="col"></div>
    <div class="col">
      <form action="{{ url_for('user.login') }}" method="post">
        <div class="row form-group">
													<div class="col-md-12">
														<label for="activities">身份</label>
                            <br>
                              <input type="radio" name="userRole" value="ADMIN" />管理员
                              <input type="radio" name="userRole" value="RESTAURANT" />商家用户
                              <input type="radio" name="userRole" value="CUSTOMER" checked />买家用户
                              <input type="radio" name="userRole" value="RIDER" checked />骑手用户
                            <br>
													</div>
												</div>
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱地址</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>

        {% for message in get_flashed_messages() %}
          <div class="form-group">
          <div class="text-danger">{{ message }}</div>

          </div>
        {% endfor %}

        <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block">立即登录</button>
        </div>

      </form>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/order.html
{% extends "base.html" %}

{% block title %}下单{% endblock %}

{% block body %}
<h1 align="center">请填写详细信息</h1>
  <div class="row mt-4">
    <div class="col"></div>
      <form action="{{ url_for('qa.send') }}" method="post">

        <div class="form-control">
          <label for="exampleInputDish">餐品名称</label>
          <input type="text" id="exampleInputDish" name="dish">
        </div>

        <div class="form-control">
          <label for="exampleInputAddress">送餐地址</label>
          <input type="text" id="exampleInputAddress" name="address">
        </div>

        <div class="form-control">
          <label for="exampleInputTele">联系电话</label>
          <input type="text" id="exampleInputTele" name="telephone">
        </div>
        <p></p>
        <button type="submit" class="btn btn-primary btn-block">提交订单</button>
      </form>
    <div class="col"></div>
  </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}外卖平台-注册{% endblock %}

{% block head %}
  <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
  <script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}


{% block body %}
<div class="row mt-4">
    <div class="col"></div>
    <div class="col">
      <form method="POST" action="{{ url_for('user.register') }}">
        <div class="col-md-12">
          <label for="activities">身份</label>
          <br>
            <input type="radio" name="userRole" value="RESTAURANT" />商家用户
            <input type="radio" name="userRole" value="CUSTOMER"  />买家用户
            <input type="radio" name="userRole" value="RIDER" checked />骑手用户
          <br>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
          <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">验证码</label>
          <div class="input-group">
            <input type="text" class="form-control" name="captcha">
            <div class="input-group-append">
               <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">用户名</label>
          <input type="text" class="form-control" name="username">
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">确认密码</label>
          <input type="password" class="form-control" name="password_confirm">
        </div>

        <button type="submit" class="btn btn-primary btn-block">立即注册</button>
      </form>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/restaurant.html
{% extends "base.html" %}

{% block title %}商家界面{% endblock %}

{% block body %}
<h1 align="center">商家界面</h1>
  <h2>  商家您好！</h2>
  <form action="{{ url_for('user.comment') }}" method="post">
    <button type="submit" class="btn btn-primary">上传菜品</button>
  </form>
{% endblock %}

templates/rider.html
{% extends "base.html" %}

{% block title %}骑手界面{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
  <h1 align="center">骑手界面</h1>
  <h2> 骑手您好！您拥有收益：{{ money }}元</h2>
  {% for waimai1 in waimai %}
    <li>
      <div class="side-question">

      </div>
      <div class="question-main">
        <div class="question-title">
          配餐：{{ waimai1.dish }}
        </div>
        <div>配送地点：{{ waimai1.delivery_address }}</div>
        <div>
          电话号码：{{ waimai1.telephone_number }}
        </div>


        <div class="question-detail">
          抵达时间：<span class="question-time">{{ waimai1.arrival_time }}</span>
        </div>
        <div>

          {% if waimai1.state == 0 %}
            <div>
              <form action="{{ url_for('qa.take_orders',dish_id=waimai1.id) }}" method="post">
                <button type="submit" class="btn btn-primary">接单</button>
              </form>
            </div>
          {% else %}
            已完成
          {% endif %}
        </div>

      </div>
    </li>

  {% endfor %}
{% endblock %}

templates/user_homepage.html
{% extends "base.html" %}

{% block title %}个人主页{% endblock %}

{% block body %}
  <h1 align="center">个人主页</h1>
  <h2> 您好！{{ user.username }}</h2>
  <h2>用户信息修改</h2>
  <form action="{{ url_for('qa.user_change') }}" method="post" enctype="multipart/form-data">
    <p>用户名<input type="text" class="form-control" id="inputUsername" name="username" value="{{ g.user.username }}">
    </p>
    <p>密码<input type="password" class="form-control" id="inputPassword" name="password" value="{{ g.user.password }}">
    </p>
    <p>邮箱<input type="email" class="form-control" id="inputEmail" name="email" value="{{ g.user.email }}">
    </p>
    <p>
      <input type="file" id="exampleInputFile" name="icon">
    </p>
    <p>
      <img src="{% if user.icon %} {{ url_for('static',filename=user.icon) }} {% else %}{{ url_for('static',filename='/images/diana2.jpg') }}{% endif %}" alt="" width="50" height="50">
    </p>
    <p>
      <button type="submit" class="btn-primary">用户信息修改</button>
    </p>
  </form>

{% endblock %}